config/routes.rb
Rails.application.routes.draw do

    root :to => 'home#index'
    
    resources :projects
    
    resources :questions do 
      resources :answers
    end
    
    resources :articles
    resources :code_snippets
    
    resources :categories do 
      member do 
        get 'show_articles'
        get 'show_blogs'
        get 'show_code_snippets'
        get 'show_questions'
      end
    end
    
    get '/tags/code_snippets' => 'code_snippets#tags'
    get '/tags/questions' => 'questions#tags'
    get '/tags/articles' => 'articles#tags'
    get '/tags/blogs' => 'blogs#tags'
   
    resources :comments
    resources :blogs
     resources :users, except: [:show, :destroy] do
      member do
        get 'user_articles'
        get 'user_blogs'
        get 'user_code_snippets'
        get 'user_questions'
        get 'profile'
        get 'subscribe'
      end
    end
   
    

    mount Bootsy::Engine => '/bootsy', as: 'bootsy'
    
    
    devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
    controllers: {omniauth_callbacks: "omniauth_callbacks"}
    
    
    devise_scope :user do
      get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
      get '/users/auth/:provider/callback' => 'omniauth_callbacks#all'
    end
    
    get 'search' => 'search#search_engine'
    get 'search/global_search_engine' => 'search#global_search_engine'
    get 'search/users_search' => 'search#users_search'
    get 'search/advance_search' => 'search#advance_search'
    

end

app/models/answer.rb
class Answer < ActiveRecord::Base
   include Bootsy::Container
   has_many :comments, as: :commentable
   belongs_to :question
   belongs_to :user
   validates :content, :presence => true

   after_create :user_points

private

  def user_points
  
    self.user.points += 10 if user_id?
    self.user.save!
  end
  
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  include Bootsy::Container
  has_many :comments, as: :commentable
  belongs_to :category
  belongs_to :user
  belongs_to :project
  validates :title,  :presence => true
  validates :content, :presence => true
  
  searchable do
    text :tags, :title
  end
  
  after_create :user_points
  
  private
  
  def user_points
  
    self.user.points += 10 if user_id?
    self.user.save!
  end
  
end

app/models/badge.rb
class Badge < ActiveRecord::Base
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  include Bootsy::Container
  has_many :comments, as: :commentable
  belongs_to :category
  belongs_to :user
  validates :title,  :presence => true
  validates :content, :presence => true
  
  searchable do
    text :tags, :title
  end
  
  after_create :user_points
  
  private
  
  def user_points
  
    self.user.points += 10 if user_id?
    self.user.save!
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  has_many :questions
  has_many :blogs
  has_many :code_snippets
end

app/models/code_snippet.rb
class CodeSnippet < ActiveRecord::Base
  include Bootsy::Container
  has_many :comments, as: :commentable
  belongs_to :category
  belongs_to :user
  belongs_to :project
  
  validates :title, presence: true
  validates :content, presence: true
  
  searchable do
    text :tags, :title
  end
  
 after_create :user_points
  
  private
  
  def user_points
  
    self.user.points += 10 if user_id?
    self.user.save!
  end
   
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  after_create :user_points
  
  private 
  
  def user_points
   count=Comment.select("user_id").where(:commentable_id =>self.commentable_id,:commentable_type=>self.commentable_type).count
   if count==1
    self.user.points += 5 if user_id?
    self.user.save!
   end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :articles
  has_many :questions
  has_many :code_snippets
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Bootsy::Container
  belongs_to :category
  belongs_to :user
  belongs_to :project
  has_many :answers
  validates :title,  :presence => true
  validates :content, :presence => true
  
  searchable do
    text :tags, :title
  end
  
  after_create :user_points
  
  private
  
  def user_points
  
    self.user.points += 10 if user_id?
    self.user.save!
  end
  
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  validates :email, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base

  mount_uploader :avatar, AvatarUploader
  
  before_save :intialize
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
         
  has_many :articles  
  has_many :questions
  has_many :comments
  has_many :code_snippets
  has_many :blogs
  has_many :answers
  
  searchable do
    text :name
  end
  
  def intialize
    self.points ||= 0 
  end
         
  def self.from_omniauth(auth)
    if auth.extra.raw_info.hd == "amzur.com"
      where(auth.slice(:provider, :uid)).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.token = auth.credentials.token
        user.secret = auth.credentials.secret
        user.email = auth.info.email
        user.name = auth.info.name
        user.remote_avatar_url = auth.info.image
        user.save!
      end
    else
      false
    end
  end
  
  def password_required?
    super && provider.blank?
  end 
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  layout "home_template", only: [:new, :edit]
  

  
  before_filter :authenticate_user!, only: [:new, :edit]
  
  before_filter :user_identification, only: :edit 
  
 
  
  
  def index
     @articles = Article.order('created_at DESC').page(params[:page]).per(4)
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = current_user.articles.new(params_articles)

    if @article.save      

      
      @subscribers = Subscription.all
      @subscribers.each do |subscriber|
      UserMailer.delay.article_notifier(subscriber, @article)
       end 
      redirect_to @article
    else
      flash[:error] = "Title and content should not be empty"
      render "new"
    end
    
  end
   
  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.page(params[:page]).per(4)
    #raise params.inspect
    @comment = Comment.new
  end
  
  def edit     
    @article = Article.find(params[:id])        
  end
  
  def update
    @article = Article.find(params[:id])
    @article.update(params_articles)
    redirect_to @article
  end
  
  def tags
    @articles = Article.where("tags LIKE ?",  "%#{params[:tag]}%").page(params[:page]).per(5)
    respond_to do |format|
      format.js
    end
  end
  
 
      
  private
   
  
  
  def params_articles
    params.require(:article).permit(:title, :content, :tags, :category_id, :project_id)
  end
  
  def user_identification
   @article = Article.find(params[:id])
   if @article.user_id ==current_user.id
   else
    flash[:notice]= "you are not authorised for this action"
    redirect_to @article
   end 
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def format_time(date_time)
    date_time.strftime("%m/%d/%Y %I:%M%p")
  end
    
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article_side_bar.html.erb
<% content_for :categories  do %>
  <ul>
    <% Category.all.limit(5).each do |category| %>
      <li><%= link_to category.title, show_articles_category_path(category) %></li>
    <% end %>        
  </ul>
<% end %>


<% content_for :users do %>
  <ul>
    <% User.all.limit(5).each do |user| %>
      <li><%= link_to user.name, user_articles_user_path(user) %></li>
    <% end %>               
  </ul>
<% end %>

<% content_for :recent_posts do %>
  <div class="title_div">Recent Articles</div>
    <div class="post_content">
      <ul>
        <% Article.all.limit(5).each do |article| %>
          <li><%= link_to truncate(article.title, :ommision => "... Read More", :length => 25), article %></li> 
        <% end %>
      </ul>
   </div>
<% end %>

<% content_for :tags do %>
  <ul>
    <% a= [] %>
      <% Article.all.map(&:tags).each do |tag| %>
        <%  a << tag.split(",") %>
      <% end %>
      <% a=  a.flatten.uniq %>
      <% a.first(5).each do |tag|%>
        <li><%= link_to tag, tags_articles_path(:tag => tag), :remote => true %></li>
      <% end %>
  </ul>
 <% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <%= render "shared/validations" %>

<%= f.label :title, "Title" %> 
  <%= f.text_field :title,:style => "margin: 0px 0px 10px; width: 800px;" %><br>
  <%= f.label :content, "Content" %>  
  <%= f.bootsy_area :content, :style => "margin: 0px 0px 10px; width: 650px; height: 221px;" %><br>
  <%= f.label :tags, "Category" %> 
  <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :title) %><br>
  <%= f.label :tags, "Project" %> 
  <%= f.select :project_id, options_from_collection_for_select(Project.all, :id, :title) %><br>
  <%= f.label :tags, "Tags" %> 
  <%= f.hidden_field :tags %> 
    <input type="text" id="tag">
    <i class="icon-plus-sign hand_sym" id="add_tag"></i><br>
    <span id="tags"></span><br/><br/>
  <%= f.submit "Submit", :class=>"btn-info pull-right"%>
  <br><br>
<% end %>
 
 <%= render "articles/article_side_bar" %>
 
<%= render "articles/script" %>

app/views/articles/_list_of_articles.html.erb
<div id="comments">
  <% articles.each do |article| %>
    <div class="comment">
        <p class="pull-right">
          <% article.tags.split(",").each do|tag| %>
            <span class="label label-info"><i class=" icon-tag"></i> <%= link_to tag, tags_articles_path(:tag => tag), :remote => true %></span>
          <% end %>
        </p>
        <p>
          <span class="label label-inverse">
            <i class="icon-briefcase"></i> 
              <%= link_to article.category.title, show_articles_category_path(article.category.id)%>
           </span>
        </p>
        <div class="clear"></div>
        
        <h4><%= link_to article.title, article_path(article.id), :class=>"post_title"  %></h4>
        <%# truncate(article.content, :ommision => "... Read More", :length => 350) %>
        <span class="content_in_list"><%= raw(article.content.rstrip) %></span>
        <%= link_to "Read More",article_path(article.id) %><br>
        <p class="pull-right posted_by">
          <i class="icon-user"></i> <%= link_to article.user.name, profile_user_path(article.user.id) %>
          <i class="icon-time"></i> <%= (article.created_at) %>
        </p>
      </div>
    <br/>
  <% end %>  
</div>

<div id="paginator">
  <%= paginate articles, :remote => true %>
</div>

<%= render "articles/article_side_bar" %>

app/views/articles/_script.html.erb
<script>
  
  function display_tags(){
    $('#tags').html("");
    $.each($('#article_tags').val().split(","), function( index, value ) {
      if(value.trim()!=""){
        $('#tags').append("<span class='label label-inverse'><span>"+value+" </span><a href='#' onclick='remove_tag(this)'>x</a></span> ");
      }    
    });
    var all_tags = "";
    $.each($('#tags span span'), function( index, value ) {
      all_tags = $(this).text().trim()+","+all_tags;
    });
    $('#article_tags').val(all_tags);
  } 
  
  
  function remove_tag(obj){
    $(obj).parent().remove();
    var all_tags = "";
    $.each($('#tags span span'), function( index, value ) {
      all_tags = $(this).text().trim()+","+all_tags;
    });
    $('#article_tags').val(all_tags);
  }
  
  display_tags();
 
  $('#tag').keyup(function(key){
    if(key.keyCode == 13){
        add_tag();
      }
  });
  
  $("#add_tag").click(function(){
        add_tag();
  });
  
 //prevent enter key form submittion 
  
  $("#tag").keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });

  function add_tag(){
      $('#tags').text($('#tag').val().trim()+","+$('#article_tags').val());
      $('#article_tags').val($('#tags').text());
      $('#tag').val("");
      display_tags();
  }
</script>

app/views/articles/_show_article.html.erb
<% if current_user.present? %>
  <% if @article.user_id == current_user.id %>
    <%= link_to "EDIT",edit_article_path(@article.id), :class=>"icon-edit pull-right" %><br/>
  <% end %>
<% end %>

<div class="clear"></div>

<p class="pull-right">
  <% @article.tags.split(',').each do |tag| %> 
  <span class="label label-info"><i class=" icon-tag"></i> <%= link_to tag, tags_articles_path(:tag => tag), :remote => true %></span>
  <% end %>
</p>

<p>
  <span class="label label-inverse"><i class="icon-briefcase"></i>
    <%= link_to @article.category.title, show_articles_category_path(@article.category.id)%>
  </span>
</p>

<h4 class="post_title">
  <%= @article.title %> 
</h4>

<p class="post_content">
  <%= raw @article.content %>
</p>

<p class="pull-down">
<b>Project:</b><%= @article.project.title %>
</p>

<%# link_to "Show All", articles_path %>
<div class="clear"></div>

<p class="pull-right posted_by">
  <i class="icon-user"></i> <%= link_to @article.user.name, profile_user_path(@article.user.id) %>
  <i class="icon-time"></i> <%= format_time(@article.created_at) %>
</p>

<div class="clear"></div>

<div class="comments_index">
  <%= render 'comments/index' %>
</div>

<div>
  <%= render 'comments/new' %>
</div>

<p class="pull-left Back">
<%= link_to "Back", articles_path %></p>

<%= render "articles/article_side_bar" %>

app/views/articles/_side_bar.html.erb
<% content_for :categories  do %>
  <ul>
    <% Category.all.limit(5).each do |category| %>
      <li><%= link_to category.title, show_articles_category_path(category) %></li>
    <% end %>        
  </ul>
<% end %>


<% content_for :users do %>
  <ul>
    <% User.all.limit(5).each do |user| %>
      <li><%= link_to user.name, user_articles_user_path(user) %></li>
    <% end %>               
  </ul>
<% end %>

<% content_for :recent_posts do %>
  <ul>
                <li><a href="#"><i class=""></i> Link </a></li>
                <li><a href="#"><i class=""></i> Link 2</a></li>
                <li><a href="#"><i class=""></i> Link 3</a></li>
                <li><a href="#"><i class=""></i> Link 4</a></li>
                <li><a href="#"><i class=""></i> Link 5</a></li>
              </ul>
<% end %>

app/views/articles/edit.html.erb
<h4> <%= @article.title %> </h4><hr>


<%= render 'form' %>

app/views/articles/index.html.erb
<div class="btn btn-link pull-right"><i class="icon-plus-sign"></i> <%= link_to "Post New Article", new_article_path %></div>
<h3 class="title">All Articles</h3>
<div class="clear"></div>

<div class="list_of_articles">
  <%= render "list_of_articles", :articles=>@articles %>
</div>

app/views/articles/index.js.erb
$(".list_of_articles").html("<%=j render  'list_of_articles', :articles=>@articles %>");

app/views/articles/new.html.erb
<h3 class="title">New Article </h3><br><hr>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="list_of_articles">
  <%= render "articles/show_article" %>
</div>

app/views/articles/show.js.erb
$(".comments_index").html("<%=j render  'comments/index', :comments=>@comments %>");

app/views/articles/tags.js.erb
$(".list_of_articles").html('<%=j render "list_of_articles", :articles => @articles %>');