config/routes.rb
Rails.application.routes.draw do

    root :to => 'home#index'
    
    resources :projects
    
    resources :questions do 
      resources :answers
    end
    
    resources :articles
    resources :code_snippets
    
    resources :categories do 
      member do 
        get 'show_articles'
        get 'show_blogs'
        get 'show_code_snippets'
        get 'show_questions'
      end
    end
    
    get '/tags/code_snippets' => 'code_snippets#tags'
    get '/tags/questions' => 'questions#tags'
    get '/tags/articles' => 'articles#tags'
    get '/tags/blogs' => 'blogs#tags'
   
    resources :comments
    resources :blogs
     resources :users, except: [:show, :destroy] do
      member do
        get 'user_articles'
        get 'user_blogs'
        get 'user_code_snippets'
        get 'user_questions'
        get 'profile'
        get 'subscribe'
      end
    end
   
    

    mount Bootsy::Engine => '/bootsy', as: 'bootsy'
    
    
    devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
    controllers: {omniauth_callbacks: "omniauth_callbacks"}
    
    
    devise_scope :user do
      get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
      get '/users/auth/:provider/callback' => 'omniauth_callbacks#all'
    end
    
    get 'search' => 'search#search_engine'
    get 'search/global_search_engine' => 'search#global_search_engine'
    get 'search/users_search' => 'search#users_search'
    get 'search/advance_search' => 'search#advance_search'
    

end

app/models/answer.rb
class Answer < ActiveRecord::Base
   include Bootsy::Container
   has_many :comments, as: :commentable
   belongs_to :question
   belongs_to :user
   validates :content, :presence => true

   after_create :user_points

private

  def user_points
  
    self.user.points += 10 if user_id?
    self.user.save!
  end
  
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  include Bootsy::Container
  has_many :comments, as: :commentable
  belongs_to :category
  belongs_to :user
  belongs_to :project
  validates :title,  :presence => true
  validates :content, :presence => true
  
  searchable do
    text :tags, :title
  end
  
  after_create :user_points
  
  private
  
  def user_points
  
    self.user.points += 10 if user_id?
    self.user.save!
  end
  
end

app/models/badge.rb
class Badge < ActiveRecord::Base
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  include Bootsy::Container
  has_many :comments, as: :commentable
  belongs_to :category
  belongs_to :user
  validates :title,  :presence => true
  validates :content, :presence => true
  
  searchable do
    text :tags, :title
  end
  
  after_create :user_points
  
  private
  
  def user_points
  
    self.user.points += 10 if user_id?
    self.user.save!
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  has_many :questions
  has_many :blogs
  has_many :code_snippets
end

app/models/code_snippet.rb
class CodeSnippet < ActiveRecord::Base
  include Bootsy::Container
  has_many :comments, as: :commentable
  belongs_to :category
  belongs_to :user
  belongs_to :project
  
  validates :title, presence: true
  validates :content, presence: true
  
  searchable do
    text :tags, :title
  end
  
 after_create :user_points
  
  private
  
  def user_points
  
    self.user.points += 10 if user_id?
    self.user.save!
  end
   
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  after_create :user_points
  
  private 
  
  def user_points
   count=Comment.select("user_id").where(:commentable_id =>self.commentable_id,:commentable_type=>self.commentable_type).count
   if count==1
    self.user.points += 5 if user_id?
    self.user.save!
   end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :articles
  has_many :questions
  has_many :code_snippets
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Bootsy::Container
  belongs_to :category
  belongs_to :user
  belongs_to :project
  has_many :answers
  validates :title,  :presence => true
  validates :content, :presence => true
  
  searchable do
    text :tags, :title
  end
  
  after_create :user_points
  
  private
  
  def user_points
  
    self.user.points += 10 if user_id?
    self.user.save!
  end
  
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  validates :email, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base

  mount_uploader :avatar, AvatarUploader
  
  before_save :intialize
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
         
  has_many :articles  
  has_many :questions
  has_many :comments
  has_many :code_snippets
  has_many :blogs
  has_many :answers
  
  searchable do
    text :name
  end
  
  def intialize
    self.points ||= 0 
  end
         
  def self.from_omniauth(auth)
    if auth.extra.raw_info.hd == "amzur.com"
      where(auth.slice(:provider, :uid)).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.token = auth.credentials.token
        user.secret = auth.credentials.secret
        user.email = auth.info.email
        user.name = auth.info.name
        user.remote_avatar_url = auth.info.image
        user.save!
      end
    else
      false
    end
  end
  
  def password_required?
    super && provider.blank?
  end 
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate_user!, only: [:users_index, :user_articles, :user_blogs, :user_code_snippets, :user_questions, :edit, :update, :profile]
  
  layout "profile_template", only: [:edit, :profile, :index]
  
  before_action :find_user, only: [:user_articles, :user_blogs, :user_code_snippets, :user_questions, :edit, :update, :profile, :new, :subscribe]
  
  def index
    @users = User.all
  end
  
  def user_articles
    @user_related_articles = @user.articles.order(:id).page(params[:page]).per(5)
    
  end
  
  def user_blogs
     @user_related_blogs = @user.blogs.order(:id).page(params[:page]).per(5)
  end
  
  def user_code_snippets
     @user_related_code_snippets = @user.code_snippets.order(:id).page(params[:page]).per(5)
  end
  
  def user_questions
     @user_related_questions = @user.questions.order(:id).page(params[:page]).per(5)
  end
  
 
  def profile
    @user_questions = @user.questions.limit(5)
    
    @user_code_snippets = @user.code_snippets.limit(5)
    
    @user_blogs = @user.blogs.limit(5)
    
    @user_articles = @user.articles.limit(5)
    
  end
  
  def edit

  end
  
  
  def update
    #@user
    if @user.id == current_user.id
      @user.update(user_params)
      redirect_to profile_user_path(@user)
     else
     redirect_to profile_user_path(@user)
     end
  end
  
  def subscribe
    Subscription.create(:email => @user.email)
    
    redirect_to profile_user_path(@user)
      
  end
  
  private
  
  def find_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :avatar, :profile_name)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def format_time(date_time)
    date_time.strftime("%m/%d/%Y %I:%M%p")
  end
    
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_articles.html.erb
  <% @user_related_articles.each do |article|%>
  <%= link_to article.title, article_path(article.id) %><hr/>
<% end %>

<div id="paginator">
  <%= paginate @user_related_articles, :remote => true %>
</div>

app/views/users/_articles_list.html.erb
<div class="articles">
<% if @user_articles.present? %>
<% @user_articles.each do |article|%>
  <%= link_to article.title, article_path(article.id) %><hr/>
<% end %>
</div>
<div class= "pull-right">
<% if @user_articles.length>5 %>
<%= link_to 'More articles',  user_articles_user_path, :remote=> true %>
<% end %>
<% else %>
<%= "No Articles" %>
<% end %>
</div>

app/views/users/_code_snippets_list.html.erb
<div class="codebases">
<% if @user_code_snippets.present? %>
<% @user_code_snippets.each do |code_snippet| %>
  <%= link_to code_snippet.title, code_snippet_path(code_snippet.id) %><hr/>
<% end %>
</div>
<div class="pull-right">
  <% if @user_code_snippets.length > 5 %>
  <%= link_to 'More codes',  user_code_snippets_user_path, :remote=> true %>
  <% end %>
<% else %>
<%= "No Code Base" %>
<% end %>
</div>

app/views/users/_data_list.html.erb
<h4 id="name"> My Contribution </h4>
       <div class="dis">
       <ul  class="nav nav-tabs" id="myTab">
          <li class="active"><a data-toggle="tab" href="#questions">Questions</a></li>
          <li><a data-toggle="tab" href="#articles">Articles</a></li>
          <li><a data-toggle="tab" href="#posts">Posts</a></li>           
          <li><a data-toggle="tab" href="#code_bases">Code bases</a></li>
       </ul>
      <div class="tab-content">
          <div id="questions" class="tab-pane fade active in">
          
              <div class="list_of_questions">
                 <%= render "questions_list" %>
              </div>
          </div>
          
          <div id="articles" class="tab-pane fade">
              
                <div class="list_of_articles">
                 <%= render "articles_list" %>
              </div>
          </div>
          
          <div id="posts" class="tab-pane fade">
            
                 <div class="list_of_blogs">
                 <%= render "blogs_list" %>
              </div>
          </div>
          
          <div id="code_bases" class="tab-pane fade">
            
                 <div class="list_of_code_snippets">
                 <%= render "code_snippets_list" %>
              </div>
          </div>
          
      </div>
      </div>
      

app/views/users/_questions.html.erb
<div class="list_of_questions">
  <% @user_related_questions.each do |question|%>
    <%= link_to question.title, question_path(question.id) %><hr/>
  <% end %>
</div>
<div id="paginator">
  <%= paginate @user_related_questions, :remote => true %>
</div>

app/views/users/_users_list.html.erb
<div class="page-description" style="margin-top: 50px;">
        <h1 id="name"> All users </h1>
         
      </div>
     <div class="clear">
     </div> 
      <div id="user-browse">
          <% @users.each do |user| %>  
            <div class="singleuser">
               <div class="user-info user-hover">
                  <% if user.avatar? %>
                    <div class="user-gravatar48">
                      <%= link_to image_tag(user.avatar_url), profile_user_path(user.id)%>
                    </div>
                  <% else %>
                    <div class="user-gravatar48">
                      <img src="/assets/user.jpeg" height="75" width="75"></img>
                    </div>
                  <%end%>
                  <div class="user-details">
                     <%= link_to user.name, profile_user_path(user.id) %><br/>
                     <span class="user-location"><%= user.email %></span><br/>                       
                     <!--   <span class="reputation-score" dir="ltr" title="reputation this month: 8093 total reputation: 187179">10 </span> -->                    <span class="user-location">Points:<%= user.points %></span>
                  </div>  
             </div>
          </div> 
       <% end %>
    </div>

     
     

app/views/users/edit.html.erb
<div id="username"> 
  <h1 id="name"> Update My Profile </h1>
</div><hr>

<%= form_for @user do |f| %>
  <div class="control-group">
    <label class="control-label" for="username">Profile Name</label>
    <div class="controls">
      <%= f.text_field :name, :id => "inputEmail", :placeholder => "Profile Name" %>
    </div>
  </div>
         
   <div class="control-group">
     <label class="control-label" for="secondname">Full Name</label>
     <div class="controls">
      <%= f.text_field :profile_name, :id => "inputEmail", :placeholder => "Full Name" %>
     </div>
   </div>
         
   <div class="control-group">
     <label class="control-label" for="inputEmail">Email</label>
     <div class="controls">
       <%= f.text_field :email, :id => "inputEmail", :placeholder => "Email", :readonly => true %>
     </div>
    </div>
         
   <div class="control-group">
     <label class="control-label" for="inputCNewPassword">Upload New Photo</label>
     <div class="controls">
       <img src=<%= @user.avatar %> width="160" height="180"/> <br>
       <%= f.file_field :avatar %><br>
     </div>
    </div>
    
    <%= f.submit "Update", :class => "btn btn-success"%>
<% end %>

app/views/users/index.html.erb
<%= render 'users/users_list' %>

app/views/users/user_articles.html.erb
<h3 class="title"><%= @user.name %></h3>

<div class="btn btn-link pull-right"><i class="icon-plus-sign"></i> <%= link_to "Post New Article", new_article_path %></div>
<div class="clear"></div>

<div class="list_of_articles">
  <%=  render 'articles/list_of_articles', :articles=>@user_related_articles %>
</div>

app/views/users/user_articles.js.erb
$(".list_of_articles").html("<%= j render 'users/articles' %>");

app/views/users/user_blogs.html.erb
<h3 class="title"><%= @user.name %></h3>

<div class="btn btn-link pull-right"><i class="icon-plus-sign"></i> <%= link_to "Create New Post", new_article_path %></div>
<div class="clear"></div>

<div class="blog_list">
  <%=  render 'blogs/list_of_blogs', :blogs=>@user_related_blogs %>
</div>

app/views/users/user_code_snippets.html.erb
<h3 class="title"><%= @user.name %></h3>

<div class="btn btn-link pull-right"><i class="icon-plus-sign"></i> <%= link_to "Post A New Code Base", new_article_path %></div>
<div class="clear"></div>

<div class="code_list">
  <%=  render 'code_snippets/list_of_code_snippets', :code_snippets=> @user_related_code_snippets %>
</div>

app/views/users/user_questions.js.erb
$(".list_of_questions").html("<%= j render 'users/questions' %>");

app/views/users/users_index.html.erb
<div class="page-description" style="margin-top: 50px;">
        <h1 id="name"> All users </h1>
          <table style="width: 100%;">
            <tbody>
              <tr>
                <td>
                  Type to find users:
                  <input id="userfilter" class="userfilter" type="text" style="margin-left: 10px;" value="" name="userfilter"></input>
                </td>
              </tr>
            </tbody>
          </table>
      </div>
     <div class="clear"></div> 
      <div id="user-browse">

           <% @users.each do |user| %>

                  <div class="user-info user-hover">
                      <div class="user-gravatar48">
                          <a href="/users/1144035/gordon-linoff">
                          <% if user.avatar? %>
                              <div class="gravatar-wrapper-48">
                                  <%= image_tag(user.avatar_url, :size => "160x180") %>
                              </div>
                          <% else %>
                              <div class="gravatar-wrapper-48">
                                   <img alt="" src="/assets/user.jpeg"></img>
                              </div>
                          <%end%>
                          </a>
                      </div>
                      <div class="user-details">
                       <%= link_to user.name, profile_user_path(user.id) %>
                       <br>
                       <span class="user-location"><%= user.email %></span>                       
                  
                    <!--   <span class="reputation-score" dir="ltr" title="reputation this month: 8093 total reputation: 187179">10 </span> -->
                      
                      </div>
                  </div>
                  <div class="clear"></div>
            <% end %>
        
      </div>
     