config/routes.rb
Rails.application.routes.draw do

    root :to => 'home#index'
    
    resources :projects
    
    resources :questions do 
      resources :answers
    end
    
    resources :articles
    resources :code_snippets
    
    resources :categories do 
      member do 
        get 'show_articles'
        get 'show_blogs'
        get 'show_code_snippets'
        get 'show_questions'
      end
    end
    
    get '/tags/code_snippets' => 'code_snippets#tags'
    get '/tags/questions' => 'questions#tags'
    get '/tags/articles' => 'articles#tags'
    get '/tags/blogs' => 'blogs#tags'
   
    resources :comments
    resources :blogs
     resources :users, except: [:show, :destroy] do
      member do
        get 'user_articles'
        get 'user_blogs'
        get 'user_code_snippets'
        get 'user_questions'
        get 'profile'
        get 'subscribe'
      end
    end
   
    

    mount Bootsy::Engine => '/bootsy', as: 'bootsy'
    
    
    devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
    controllers: {omniauth_callbacks: "omniauth_callbacks"}
    
    
    devise_scope :user do
      get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
      get '/users/auth/:provider/callback' => 'omniauth_callbacks#all'
    end
    
    get 'search' => 'search#search_engine'
    get 'search/global_search_engine' => 'search#global_search_engine'
    get 'search/users_search' => 'search#users_search'
    get 'search/advance_search' => 'search#advance_search'
    

end

app/models/answer.rb
class Answer < ActiveRecord::Base
   include Bootsy::Container
   has_many :comments, as: :commentable
   belongs_to :question
   belongs_to :user
   validates :content, :presence => true

   after_create :user_points

private

  def user_points
  
    self.user.points += 10 if user_id?
    self.user.save!
  end
  
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  include Bootsy::Container
  has_many :comments, as: :commentable
  belongs_to :category
  belongs_to :user
  belongs_to :project
  validates :title,  :presence => true
  validates :content, :presence => true
  
  searchable do
    text :tags, :title
  end
  
  after_create :user_points
  
  private
  
  def user_points
  
    self.user.points += 10 if user_id?
    self.user.save!
  end
  
end

app/models/badge.rb
class Badge < ActiveRecord::Base
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  include Bootsy::Container
  has_many :comments, as: :commentable
  belongs_to :category
  belongs_to :user
  validates :title,  :presence => true
  validates :content, :presence => true
  
  searchable do
    text :tags, :title
  end
  
  after_create :user_points
  
  private
  
  def user_points
  
    self.user.points += 10 if user_id?
    self.user.save!
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  has_many :questions
  has_many :blogs
  has_many :code_snippets
end

app/models/code_snippet.rb
class CodeSnippet < ActiveRecord::Base
  include Bootsy::Container
  has_many :comments, as: :commentable
  belongs_to :category
  belongs_to :user
  belongs_to :project
  
  validates :title, presence: true
  validates :content, presence: true
  
  searchable do
    text :tags, :title
  end
  
 after_create :user_points
  
  private
  
  def user_points
  
    self.user.points += 10 if user_id?
    self.user.save!
  end
   
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  after_create :user_points
  
  private 
  
  def user_points
   count=Comment.select("user_id").where(:commentable_id =>self.commentable_id,:commentable_type=>self.commentable_type).count
   if count==1
    self.user.points += 5 if user_id?
    self.user.save!
   end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :articles
  has_many :questions
  has_many :code_snippets
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Bootsy::Container
  belongs_to :category
  belongs_to :user
  belongs_to :project
  has_many :answers
  validates :title,  :presence => true
  validates :content, :presence => true
  
  searchable do
    text :tags, :title
  end
  
  after_create :user_points
  
  private
  
  def user_points
  
    self.user.points += 10 if user_id?
    self.user.save!
  end
  
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  validates :email, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base

  mount_uploader :avatar, AvatarUploader
  
  before_save :intialize
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
         
  has_many :articles  
  has_many :questions
  has_many :comments
  has_many :code_snippets
  has_many :blogs
  has_many :answers
  
  searchable do
    text :name
  end
  
  def intialize
    self.points ||= 0 
  end
         
  def self.from_omniauth(auth)
    if auth.extra.raw_info.hd == "amzur.com"
      where(auth.slice(:provider, :uid)).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.token = auth.credentials.token
        user.secret = auth.credentials.secret
        user.email = auth.info.email
        user.name = auth.info.name
        user.remote_avatar_url = auth.info.image
        user.save!
      end
    else
      false
    end
  end
  
  def password_required?
    super && provider.blank?
  end 
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  layout "home_template", only: [:new, :edit, :create, :show, :index]
  before_action :find_category, only: [:show_articles, :show_blogs, :show_code_snippets, :show_questions]
  
  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(params_categories)
    @category.save
    redirect_to @category
  end
   
  def show
    @category = Category.find(params[:id])
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    @category.update(params_categories)
    redirect_to @category
  end
  
  def show_articles
    @category_related_articles = @category.articles.order(:id).page(params[:page]).per(5)
  end
  
  def show_blogs
     @category_related_blogs =@category.blogs.order(:id).page(params[:page]).per(5)
  end
  
  def show_code_snippets
     @category_related_code_snippets = @category.code_snippets.order(:id).page(params[:page]).per(5)
  end
  
  def show_questions
     @category_related_questions = @category.questions.order(:id).page(params[:page]).per(5)
  end
     
  private
  
  def params_categories
    params.require(:category).permit(:title)
  end
  
  def find_category
    @category=Category.find(params[:id])
  end 
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def format_time(date_time)
    date_time.strftime("%m/%d/%Y %I:%M%p")
  end
    
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |c| %>


  <%= c.label :title, "Category Name" %> 
  <%= c.text_field :title %><br>

  <%= c.submit "Submit"%> 
<% end %>

app/views/categories/edit.html.erb
<h3 class="title">Edit Category</h3><br><hr>


<%= render 'form' %>


<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h3 class="title">All Categories </h3><br><hr>
&nbsp;&nbsp;<%= link_to "New Category", new_category_path %><hr>
<% @categories.each do |category| %>
<b><%= category.title %></b><br>
<%= link_to "Edit",edit_category_path(category.id) %>&nbsp;&nbsp;&nbsp;&nbsp;
<%= link_to "Show",category_path(category.id) %><hr>
<% end %>  <br>

app/views/categories/new.html.erb
<h3 class="title">Add New Category</h3><br><br><br>

<%= render 'form' %>

<%= link_to "Back", categories_path %>

app/views/categories/show.html.erb
<h3 class="title">Show Category</h3><br><hr>
<p><b>Category Name:</b><%= @category.title %></p></br>
<%= link_to "Edit",edit_category_path(@category.id) %>&nbsp;&nbsp;
<%= link_to "Show All", categories_path %>&nbsp;&nbsp;
<%= link_to "Back", categories_path %>&nbsp;&nbsp;

app/views/categories/show_articles.html.erb
<h3 class="title"><%= @category.title %></h3>

<div class="btn btn-link pull-right"><i class="icon-plus-sign"></i> <%= link_to "Post New Article", new_article_path %></div>
<div class="clear"></div>

<div class="list_of_articles">
  <%=  render 'articles/list_of_articles', :articles=>@category_related_articles %>
</div>

app/views/categories/show_articles.js.erb
$(".list_of_articles").html("<%=j render 'articles/list_of_articles', :articles=>@category_related_articles %>");

app/views/categories/show_blogs.html.erb
<h3 class="title"><%= @category.title %></h3>


<div class="btn btn-link pull-right"><i class="icon-plus-sign"></i> <%= link_to "Create New Post", new_article_path %></div>
<div class="clear"></div>

<div class="blog_list">
  <%=  render 'blogs/list_of_blogs', :blogs=>@category_related_blogs %>
</div>

app/views/categories/show_blogs.js.erb
$(".blog_list").html("<%=j render 'blogs/list_of_blogs', :blogs=>@category_related_blogs %>");

app/views/categories/show_code_snippets.html.erb
<h3 class="title"><%= @category.title %></h3>


<div class="btn btn-link pull-right"><i class="icon-plus-sign"></i> <%= link_to "Post A New Code Base", new_article_path %></div>
<div class="clear"></div>

<div class="code_list">
  <%= render "code_snippets/list_of_code_snippets", :code_snippets=> @category_related_code_snippets %>
</div>

app/views/categories/show_code_snippets.js.erb
$(".code_list").html("<%=j render 'code_snippets/list_of_code_snippets', :code_snippets=> @category_related_code_snippets %>");

app/views/categories/show_questions.html.erb
<h3 class="title"><%= @category.title %></h3>


<div class="btn btn-link pull-right"><i class="icon-plus-sign"></i> <%= link_to "Post A New Question", new_article_path %></div>
<div class="clear"></div>

<div class="questions_list">
  <%=  render 'questions/list_of_questions', :questions=>@category_related_questions %>
</div>

app/views/categories/show_questions.js.erb
$(".questions_list").html("<%=j render 'questions/list_of_questions', :questions=>@category_related_questions %>");